// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settlement.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "settlement.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace price {

namespace {

const ::google::protobuf::Descriptor* Settlement_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Settlement_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_settlement_2eproto() {
  protobuf_AddDesc_settlement_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "settlement.proto");
  GOOGLE_CHECK(file != NULL);
  Settlement_descriptor_ = file->message_type(0);
  static const int Settlement_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settlement, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settlement, price_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settlement, auth_),
  };
  Settlement_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Settlement_descriptor_,
      Settlement::default_instance_,
      Settlement_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settlement, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Settlement, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Settlement));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_settlement_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Settlement_descriptor_, &Settlement::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_settlement_2eproto() {
  delete Settlement::default_instance_;
  delete Settlement_reflection_;
}

void protobuf_AddDesc_settlement_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020settlement.proto\022\005price\":\n\nSettlement\022"
    "\017\n\007version\030\001 \001(\r\022\r\n\005price\030\002 \002(\014\022\014\n\004auth\030"
    "\003 \001(\014", 85);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "settlement.proto", &protobuf_RegisterTypes);
  Settlement::default_instance_ = new Settlement();
  Settlement::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_settlement_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_settlement_2eproto {
  StaticDescriptorInitializer_settlement_2eproto() {
    protobuf_AddDesc_settlement_2eproto();
  }
} static_descriptor_initializer_settlement_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Settlement::kVersionFieldNumber;
const int Settlement::kPriceFieldNumber;
const int Settlement::kAuthFieldNumber;
#endif  // !_MSC_VER

Settlement::Settlement()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:price.Settlement)
}

void Settlement::InitAsDefaultInstance() {
}

Settlement::Settlement(const Settlement& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:price.Settlement)
}

void Settlement::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  version_ = 0u;
  price_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  auth_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Settlement::~Settlement() {
  // @@protoc_insertion_point(destructor:price.Settlement)
  SharedDtor();
}

void Settlement::SharedDtor() {
  if (price_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete price_;
  }
  if (auth_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete auth_;
  }
  if (this != default_instance_) {
  }
}

void Settlement::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Settlement::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Settlement_descriptor_;
}

const Settlement& Settlement::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_settlement_2eproto();
  return *default_instance_;
}

Settlement* Settlement::default_instance_ = NULL;

Settlement* Settlement::New() const {
  return new Settlement;
}

void Settlement::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    version_ = 0u;
    if (has_price()) {
      if (price_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        price_->clear();
      }
    }
    if (has_auth()) {
      if (auth_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        auth_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Settlement::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:price.Settlement)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 version = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &version_)));
          set_has_version();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_price;
        break;
      }

      // required bytes price = 2;
      case 2: {
        if (tag == 18) {
         parse_price:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_price()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_auth;
        break;
      }

      // optional bytes auth = 3;
      case 3: {
        if (tag == 26) {
         parse_auth:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_auth()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:price.Settlement)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:price.Settlement)
  return false;
#undef DO_
}

void Settlement::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:price.Settlement)
  // optional uint32 version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->version(), output);
  }

  // required bytes price = 2;
  if (has_price()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->price(), output);
  }

  // optional bytes auth = 3;
  if (has_auth()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->auth(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:price.Settlement)
}

::google::protobuf::uint8* Settlement::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:price.Settlement)
  // optional uint32 version = 1;
  if (has_version()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->version(), target);
  }

  // required bytes price = 2;
  if (has_price()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->price(), target);
  }

  // optional bytes auth = 3;
  if (has_auth()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->auth(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:price.Settlement)
  return target;
}

int Settlement::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 version = 1;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->version());
    }

    // required bytes price = 2;
    if (has_price()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->price());
    }

    // optional bytes auth = 3;
    if (has_auth()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->auth());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Settlement::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Settlement* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Settlement*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Settlement::MergeFrom(const Settlement& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
    if (from.has_price()) {
      set_price(from.price());
    }
    if (from.has_auth()) {
      set_auth(from.auth());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Settlement::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Settlement::CopyFrom(const Settlement& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Settlement::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;

  return true;
}

void Settlement::Swap(Settlement* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    std::swap(price_, other->price_);
    std::swap(auth_, other->auth_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Settlement::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Settlement_descriptor_;
  metadata.reflection = Settlement_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace price

// @@protoc_insertion_point(global_scope)
