// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: detail_info.proto

#ifndef PROTOBUF_detail_5finfo_2eproto__INCLUDED
#define PROTOBUF_detail_5finfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace pxene {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_detail_5finfo_2eproto();
void protobuf_AssignDesc_detail_5finfo_2eproto();
void protobuf_ShutdownFile_detail_5finfo_2eproto();

class DetailReqMessage;
class DetailReqMessage_ImpDetail;
class DetailReqMessage_ImpDetail_Policy;
class DetailReqMessage_ImpDetail_Creative;
class DetailReqMessage_Policy;

// ===================================================================

class DetailReqMessage_ImpDetail_Policy : public ::google::protobuf::Message {
 public:
  DetailReqMessage_ImpDetail_Policy();
  virtual ~DetailReqMessage_ImpDetail_Policy();

  DetailReqMessage_ImpDetail_Policy(const DetailReqMessage_ImpDetail_Policy& from);

  inline DetailReqMessage_ImpDetail_Policy& operator=(const DetailReqMessage_ImpDetail_Policy& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DetailReqMessage_ImpDetail_Policy& default_instance();

  void Swap(DetailReqMessage_ImpDetail_Policy* other);

  // implements Message ----------------------------------------------

  DetailReqMessage_ImpDetail_Policy* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DetailReqMessage_ImpDetail_Policy& from);
  void MergeFrom(const DetailReqMessage_ImpDetail_Policy& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional int32 nbr = 2;
  inline bool has_nbr() const;
  inline void clear_nbr();
  static const int kNbrFieldNumber = 2;
  inline ::google::protobuf::int32 nbr() const;
  inline void set_nbr(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.pxene.proto.DetailReqMessage.ImpDetail.Policy)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_nbr();
  inline void clear_has_nbr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 nbr_;
  friend void  protobuf_AddDesc_detail_5finfo_2eproto();
  friend void protobuf_AssignDesc_detail_5finfo_2eproto();
  friend void protobuf_ShutdownFile_detail_5finfo_2eproto();

  void InitAsDefaultInstance();
  static DetailReqMessage_ImpDetail_Policy* default_instance_;
};
// -------------------------------------------------------------------

class DetailReqMessage_ImpDetail_Creative : public ::google::protobuf::Message {
 public:
  DetailReqMessage_ImpDetail_Creative();
  virtual ~DetailReqMessage_ImpDetail_Creative();

  DetailReqMessage_ImpDetail_Creative(const DetailReqMessage_ImpDetail_Creative& from);

  inline DetailReqMessage_ImpDetail_Creative& operator=(const DetailReqMessage_ImpDetail_Creative& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DetailReqMessage_ImpDetail_Creative& default_instance();

  void Swap(DetailReqMessage_ImpDetail_Creative* other);

  // implements Message ----------------------------------------------

  DetailReqMessage_ImpDetail_Creative* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DetailReqMessage_ImpDetail_Creative& from);
  void MergeFrom(const DetailReqMessage_ImpDetail_Creative& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 mapid = 1;
  inline bool has_mapid() const;
  inline void clear_mapid();
  static const int kMapidFieldNumber = 1;
  inline ::google::protobuf::int32 mapid() const;
  inline void set_mapid(::google::protobuf::int32 value);

  // optional int32 nbr = 2;
  inline bool has_nbr() const;
  inline void clear_nbr();
  static const int kNbrFieldNumber = 2;
  inline ::google::protobuf::int32 nbr() const;
  inline void set_nbr(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.pxene.proto.DetailReqMessage.ImpDetail.Creative)
 private:
  inline void set_has_mapid();
  inline void clear_has_mapid();
  inline void set_has_nbr();
  inline void clear_has_nbr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 mapid_;
  ::google::protobuf::int32 nbr_;
  friend void  protobuf_AddDesc_detail_5finfo_2eproto();
  friend void protobuf_AssignDesc_detail_5finfo_2eproto();
  friend void protobuf_ShutdownFile_detail_5finfo_2eproto();

  void InitAsDefaultInstance();
  static DetailReqMessage_ImpDetail_Creative* default_instance_;
};
// -------------------------------------------------------------------

class DetailReqMessage_ImpDetail : public ::google::protobuf::Message {
 public:
  DetailReqMessage_ImpDetail();
  virtual ~DetailReqMessage_ImpDetail();

  DetailReqMessage_ImpDetail(const DetailReqMessage_ImpDetail& from);

  inline DetailReqMessage_ImpDetail& operator=(const DetailReqMessage_ImpDetail& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DetailReqMessage_ImpDetail& default_instance();

  void Swap(DetailReqMessage_ImpDetail* other);

  // implements Message ----------------------------------------------

  DetailReqMessage_ImpDetail* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DetailReqMessage_ImpDetail& from);
  void MergeFrom(const DetailReqMessage_ImpDetail& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef DetailReqMessage_ImpDetail_Policy Policy;
  typedef DetailReqMessage_ImpDetail_Creative Creative;

  // accessors -------------------------------------------------------

  // required string impId = 1;
  inline bool has_impid() const;
  inline void clear_impid();
  static const int kImpIdFieldNumber = 1;
  inline const ::std::string& impid() const;
  inline void set_impid(const ::std::string& value);
  inline void set_impid(const char* value);
  inline void set_impid(const char* value, size_t size);
  inline ::std::string* mutable_impid();
  inline ::std::string* release_impid();
  inline void set_allocated_impid(::std::string* impid);

  // optional int32 nbr = 2;
  inline bool has_nbr() const;
  inline void clear_nbr();
  static const int kNbrFieldNumber = 2;
  inline ::google::protobuf::int32 nbr() const;
  inline void set_nbr(::google::protobuf::int32 value);

  // repeated .com.pxene.proto.DetailReqMessage.ImpDetail.Policy policies = 3;
  inline int policies_size() const;
  inline void clear_policies();
  static const int kPoliciesFieldNumber = 3;
  inline const ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy& policies(int index) const;
  inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy* mutable_policies(int index);
  inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy* add_policies();
  inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy >&
      policies() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy >*
      mutable_policies();

  // repeated .com.pxene.proto.DetailReqMessage.ImpDetail.Creative creatives = 4;
  inline int creatives_size() const;
  inline void clear_creatives();
  static const int kCreativesFieldNumber = 4;
  inline const ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative& creatives(int index) const;
  inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative* mutable_creatives(int index);
  inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative* add_creatives();
  inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative >&
      creatives() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative >*
      mutable_creatives();

  // optional int32 type = 5;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 5;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional int32 width = 6;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 6;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 height = 7;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 7;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.pxene.proto.DetailReqMessage.ImpDetail)
 private:
  inline void set_has_impid();
  inline void clear_has_impid();
  inline void set_has_nbr();
  inline void clear_has_nbr();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* impid_;
  ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy > policies_;
  ::google::protobuf::int32 nbr_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative > creatives_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  friend void  protobuf_AddDesc_detail_5finfo_2eproto();
  friend void protobuf_AssignDesc_detail_5finfo_2eproto();
  friend void protobuf_ShutdownFile_detail_5finfo_2eproto();

  void InitAsDefaultInstance();
  static DetailReqMessage_ImpDetail* default_instance_;
};
// -------------------------------------------------------------------

class DetailReqMessage_Policy : public ::google::protobuf::Message {
 public:
  DetailReqMessage_Policy();
  virtual ~DetailReqMessage_Policy();

  DetailReqMessage_Policy(const DetailReqMessage_Policy& from);

  inline DetailReqMessage_Policy& operator=(const DetailReqMessage_Policy& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DetailReqMessage_Policy& default_instance();

  void Swap(DetailReqMessage_Policy* other);

  // implements Message ----------------------------------------------

  DetailReqMessage_Policy* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DetailReqMessage_Policy& from);
  void MergeFrom(const DetailReqMessage_Policy& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional int32 nbr = 2;
  inline bool has_nbr() const;
  inline void clear_nbr();
  static const int kNbrFieldNumber = 2;
  inline ::google::protobuf::int32 nbr() const;
  inline void set_nbr(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.pxene.proto.DetailReqMessage.Policy)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_nbr();
  inline void clear_has_nbr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 nbr_;
  friend void  protobuf_AddDesc_detail_5finfo_2eproto();
  friend void protobuf_AssignDesc_detail_5finfo_2eproto();
  friend void protobuf_ShutdownFile_detail_5finfo_2eproto();

  void InitAsDefaultInstance();
  static DetailReqMessage_Policy* default_instance_;
};
// -------------------------------------------------------------------

class DetailReqMessage : public ::google::protobuf::Message {
 public:
  DetailReqMessage();
  virtual ~DetailReqMessage();

  DetailReqMessage(const DetailReqMessage& from);

  inline DetailReqMessage& operator=(const DetailReqMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DetailReqMessage& default_instance();

  void Swap(DetailReqMessage* other);

  // implements Message ----------------------------------------------

  DetailReqMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DetailReqMessage& from);
  void MergeFrom(const DetailReqMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef DetailReqMessage_ImpDetail ImpDetail;
  typedef DetailReqMessage_Policy Policy;

  // accessors -------------------------------------------------------

  // optional string version = 1 [default = "1.0.6"];
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline const ::std::string& version() const;
  inline void set_version(const ::std::string& value);
  inline void set_version(const char* value);
  inline void set_version(const char* value, size_t size);
  inline ::std::string* mutable_version();
  inline ::std::string* release_version();
  inline void set_allocated_version(::std::string* version);

  // optional string bid_server_flag = 2;
  inline bool has_bid_server_flag() const;
  inline void clear_bid_server_flag();
  static const int kBidServerFlagFieldNumber = 2;
  inline const ::std::string& bid_server_flag() const;
  inline void set_bid_server_flag(const ::std::string& value);
  inline void set_bid_server_flag(const char* value);
  inline void set_bid_server_flag(const char* value, size_t size);
  inline ::std::string* mutable_bid_server_flag();
  inline ::std::string* release_bid_server_flag();
  inline void set_allocated_bid_server_flag(::std::string* bid_server_flag);

  // optional string requestId = 3;
  inline bool has_requestid() const;
  inline void clear_requestid();
  static const int kRequestIdFieldNumber = 3;
  inline const ::std::string& requestid() const;
  inline void set_requestid(const ::std::string& value);
  inline void set_requestid(const char* value);
  inline void set_requestid(const char* value, size_t size);
  inline ::std::string* mutable_requestid();
  inline ::std::string* release_requestid();
  inline void set_allocated_requestid(::std::string* requestid);

  // optional int64 time = 4;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 4;
  inline ::google::protobuf::int64 time() const;
  inline void set_time(::google::protobuf::int64 value);

  // optional int32 adxid = 5;
  inline bool has_adxid() const;
  inline void clear_adxid();
  static const int kAdxidFieldNumber = 5;
  inline ::google::protobuf::int32 adxid() const;
  inline void set_adxid(::google::protobuf::int32 value);

  // optional string appid = 6;
  inline bool has_appid() const;
  inline void clear_appid();
  static const int kAppidFieldNumber = 6;
  inline const ::std::string& appid() const;
  inline void set_appid(const ::std::string& value);
  inline void set_appid(const char* value);
  inline void set_appid(const char* value, size_t size);
  inline ::std::string* mutable_appid();
  inline ::std::string* release_appid();
  inline void set_allocated_appid(::std::string* appid);

  // optional int32 devicetype = 9;
  inline bool has_devicetype() const;
  inline void clear_devicetype();
  static const int kDevicetypeFieldNumber = 9;
  inline ::google::protobuf::int32 devicetype() const;
  inline void set_devicetype(::google::protobuf::int32 value);

  // optional int32 os = 10;
  inline bool has_os() const;
  inline void clear_os();
  static const int kOsFieldNumber = 10;
  inline ::google::protobuf::int32 os() const;
  inline void set_os(::google::protobuf::int32 value);

  // optional int64 city = 11;
  inline bool has_city() const;
  inline void clear_city();
  static const int kCityFieldNumber = 11;
  inline ::google::protobuf::int64 city() const;
  inline void set_city(::google::protobuf::int64 value);

  // optional int32 connectiontype = 12;
  inline bool has_connectiontype() const;
  inline void clear_connectiontype();
  static const int kConnectiontypeFieldNumber = 12;
  inline ::google::protobuf::int32 connectiontype() const;
  inline void set_connectiontype(::google::protobuf::int32 value);

  // optional int32 carrier = 13;
  inline bool has_carrier() const;
  inline void clear_carrier();
  static const int kCarrierFieldNumber = 13;
  inline ::google::protobuf::int32 carrier() const;
  inline void set_carrier(::google::protobuf::int32 value);

  // optional int32 nbr = 14;
  inline bool has_nbr() const;
  inline void clear_nbr();
  static const int kNbrFieldNumber = 14;
  inline ::google::protobuf::int32 nbr() const;
  inline void set_nbr(::google::protobuf::int32 value);

  // repeated .com.pxene.proto.DetailReqMessage.ImpDetail impBidDetail = 15;
  inline int impbiddetail_size() const;
  inline void clear_impbiddetail();
  static const int kImpBidDetailFieldNumber = 15;
  inline const ::com::pxene::proto::DetailReqMessage_ImpDetail& impbiddetail(int index) const;
  inline ::com::pxene::proto::DetailReqMessage_ImpDetail* mutable_impbiddetail(int index);
  inline ::com::pxene::proto::DetailReqMessage_ImpDetail* add_impbiddetail();
  inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail >&
      impbiddetail() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail >*
      mutable_impbiddetail();

  // repeated .com.pxene.proto.DetailReqMessage.Policy policies = 16;
  inline int policies_size() const;
  inline void clear_policies();
  static const int kPoliciesFieldNumber = 16;
  inline const ::com::pxene::proto::DetailReqMessage_Policy& policies(int index) const;
  inline ::com::pxene::proto::DetailReqMessage_Policy* mutable_policies(int index);
  inline ::com::pxene::proto::DetailReqMessage_Policy* add_policies();
  inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_Policy >&
      policies() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_Policy >*
      mutable_policies();

  // @@protoc_insertion_point(class_scope:com.pxene.proto.DetailReqMessage)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_bid_server_flag();
  inline void clear_has_bid_server_flag();
  inline void set_has_requestid();
  inline void clear_has_requestid();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_adxid();
  inline void clear_has_adxid();
  inline void set_has_appid();
  inline void clear_has_appid();
  inline void set_has_devicetype();
  inline void clear_has_devicetype();
  inline void set_has_os();
  inline void clear_has_os();
  inline void set_has_city();
  inline void clear_has_city();
  inline void set_has_connectiontype();
  inline void clear_has_connectiontype();
  inline void set_has_carrier();
  inline void clear_has_carrier();
  inline void set_has_nbr();
  inline void clear_has_nbr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  static ::std::string* _default_version_;
  ::std::string* version_;
  ::std::string* bid_server_flag_;
  ::std::string* requestid_;
  ::google::protobuf::int64 time_;
  ::std::string* appid_;
  ::google::protobuf::int32 adxid_;
  ::google::protobuf::int32 devicetype_;
  ::google::protobuf::int64 city_;
  ::google::protobuf::int32 os_;
  ::google::protobuf::int32 connectiontype_;
  ::google::protobuf::int32 carrier_;
  ::google::protobuf::int32 nbr_;
  ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail > impbiddetail_;
  ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_Policy > policies_;
  friend void  protobuf_AddDesc_detail_5finfo_2eproto();
  friend void protobuf_AssignDesc_detail_5finfo_2eproto();
  friend void protobuf_ShutdownFile_detail_5finfo_2eproto();

  void InitAsDefaultInstance();
  static DetailReqMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// DetailReqMessage_ImpDetail_Policy

// required int32 id = 1;
inline bool DetailReqMessage_ImpDetail_Policy::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetailReqMessage_ImpDetail_Policy::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DetailReqMessage_ImpDetail_Policy::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DetailReqMessage_ImpDetail_Policy::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail_Policy::id() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.Policy.id)
  return id_;
}
inline void DetailReqMessage_ImpDetail_Policy::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.Policy.id)
}

// optional int32 nbr = 2;
inline bool DetailReqMessage_ImpDetail_Policy::has_nbr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetailReqMessage_ImpDetail_Policy::set_has_nbr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DetailReqMessage_ImpDetail_Policy::clear_has_nbr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DetailReqMessage_ImpDetail_Policy::clear_nbr() {
  nbr_ = 0;
  clear_has_nbr();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail_Policy::nbr() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.Policy.nbr)
  return nbr_;
}
inline void DetailReqMessage_ImpDetail_Policy::set_nbr(::google::protobuf::int32 value) {
  set_has_nbr();
  nbr_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.Policy.nbr)
}

// -------------------------------------------------------------------

// DetailReqMessage_ImpDetail_Creative

// optional int32 mapid = 1;
inline bool DetailReqMessage_ImpDetail_Creative::has_mapid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetailReqMessage_ImpDetail_Creative::set_has_mapid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DetailReqMessage_ImpDetail_Creative::clear_has_mapid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DetailReqMessage_ImpDetail_Creative::clear_mapid() {
  mapid_ = 0;
  clear_has_mapid();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail_Creative::mapid() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.Creative.mapid)
  return mapid_;
}
inline void DetailReqMessage_ImpDetail_Creative::set_mapid(::google::protobuf::int32 value) {
  set_has_mapid();
  mapid_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.Creative.mapid)
}

// optional int32 nbr = 2;
inline bool DetailReqMessage_ImpDetail_Creative::has_nbr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetailReqMessage_ImpDetail_Creative::set_has_nbr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DetailReqMessage_ImpDetail_Creative::clear_has_nbr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DetailReqMessage_ImpDetail_Creative::clear_nbr() {
  nbr_ = 0;
  clear_has_nbr();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail_Creative::nbr() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.Creative.nbr)
  return nbr_;
}
inline void DetailReqMessage_ImpDetail_Creative::set_nbr(::google::protobuf::int32 value) {
  set_has_nbr();
  nbr_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.Creative.nbr)
}

// -------------------------------------------------------------------

// DetailReqMessage_ImpDetail

// required string impId = 1;
inline bool DetailReqMessage_ImpDetail::has_impid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetailReqMessage_ImpDetail::set_has_impid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DetailReqMessage_ImpDetail::clear_has_impid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DetailReqMessage_ImpDetail::clear_impid() {
  if (impid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    impid_->clear();
  }
  clear_has_impid();
}
inline const ::std::string& DetailReqMessage_ImpDetail::impid() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.impId)
  return *impid_;
}
inline void DetailReqMessage_ImpDetail::set_impid(const ::std::string& value) {
  set_has_impid();
  if (impid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    impid_ = new ::std::string;
  }
  impid_->assign(value);
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.impId)
}
inline void DetailReqMessage_ImpDetail::set_impid(const char* value) {
  set_has_impid();
  if (impid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    impid_ = new ::std::string;
  }
  impid_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.pxene.proto.DetailReqMessage.ImpDetail.impId)
}
inline void DetailReqMessage_ImpDetail::set_impid(const char* value, size_t size) {
  set_has_impid();
  if (impid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    impid_ = new ::std::string;
  }
  impid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.pxene.proto.DetailReqMessage.ImpDetail.impId)
}
inline ::std::string* DetailReqMessage_ImpDetail::mutable_impid() {
  set_has_impid();
  if (impid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    impid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.ImpDetail.impId)
  return impid_;
}
inline ::std::string* DetailReqMessage_ImpDetail::release_impid() {
  clear_has_impid();
  if (impid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = impid_;
    impid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DetailReqMessage_ImpDetail::set_allocated_impid(::std::string* impid) {
  if (impid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete impid_;
  }
  if (impid) {
    set_has_impid();
    impid_ = impid;
  } else {
    clear_has_impid();
    impid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.pxene.proto.DetailReqMessage.ImpDetail.impId)
}

// optional int32 nbr = 2;
inline bool DetailReqMessage_ImpDetail::has_nbr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetailReqMessage_ImpDetail::set_has_nbr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DetailReqMessage_ImpDetail::clear_has_nbr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DetailReqMessage_ImpDetail::clear_nbr() {
  nbr_ = 0;
  clear_has_nbr();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail::nbr() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.nbr)
  return nbr_;
}
inline void DetailReqMessage_ImpDetail::set_nbr(::google::protobuf::int32 value) {
  set_has_nbr();
  nbr_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.nbr)
}

// repeated .com.pxene.proto.DetailReqMessage.ImpDetail.Policy policies = 3;
inline int DetailReqMessage_ImpDetail::policies_size() const {
  return policies_.size();
}
inline void DetailReqMessage_ImpDetail::clear_policies() {
  policies_.Clear();
}
inline const ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy& DetailReqMessage_ImpDetail::policies(int index) const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.policies)
  return policies_.Get(index);
}
inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy* DetailReqMessage_ImpDetail::mutable_policies(int index) {
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.ImpDetail.policies)
  return policies_.Mutable(index);
}
inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy* DetailReqMessage_ImpDetail::add_policies() {
  // @@protoc_insertion_point(field_add:com.pxene.proto.DetailReqMessage.ImpDetail.policies)
  return policies_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy >&
DetailReqMessage_ImpDetail::policies() const {
  // @@protoc_insertion_point(field_list:com.pxene.proto.DetailReqMessage.ImpDetail.policies)
  return policies_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Policy >*
DetailReqMessage_ImpDetail::mutable_policies() {
  // @@protoc_insertion_point(field_mutable_list:com.pxene.proto.DetailReqMessage.ImpDetail.policies)
  return &policies_;
}

// repeated .com.pxene.proto.DetailReqMessage.ImpDetail.Creative creatives = 4;
inline int DetailReqMessage_ImpDetail::creatives_size() const {
  return creatives_.size();
}
inline void DetailReqMessage_ImpDetail::clear_creatives() {
  creatives_.Clear();
}
inline const ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative& DetailReqMessage_ImpDetail::creatives(int index) const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.creatives)
  return creatives_.Get(index);
}
inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative* DetailReqMessage_ImpDetail::mutable_creatives(int index) {
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.ImpDetail.creatives)
  return creatives_.Mutable(index);
}
inline ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative* DetailReqMessage_ImpDetail::add_creatives() {
  // @@protoc_insertion_point(field_add:com.pxene.proto.DetailReqMessage.ImpDetail.creatives)
  return creatives_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative >&
DetailReqMessage_ImpDetail::creatives() const {
  // @@protoc_insertion_point(field_list:com.pxene.proto.DetailReqMessage.ImpDetail.creatives)
  return creatives_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail_Creative >*
DetailReqMessage_ImpDetail::mutable_creatives() {
  // @@protoc_insertion_point(field_mutable_list:com.pxene.proto.DetailReqMessage.ImpDetail.creatives)
  return &creatives_;
}

// optional int32 type = 5;
inline bool DetailReqMessage_ImpDetail::has_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DetailReqMessage_ImpDetail::set_has_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DetailReqMessage_ImpDetail::clear_has_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DetailReqMessage_ImpDetail::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail::type() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.type)
  return type_;
}
inline void DetailReqMessage_ImpDetail::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.type)
}

// optional int32 width = 6;
inline bool DetailReqMessage_ImpDetail::has_width() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DetailReqMessage_ImpDetail::set_has_width() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DetailReqMessage_ImpDetail::clear_has_width() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DetailReqMessage_ImpDetail::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail::width() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.width)
  return width_;
}
inline void DetailReqMessage_ImpDetail::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.width)
}

// optional int32 height = 7;
inline bool DetailReqMessage_ImpDetail::has_height() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void DetailReqMessage_ImpDetail::set_has_height() {
  _has_bits_[0] |= 0x00000040u;
}
inline void DetailReqMessage_ImpDetail::clear_has_height() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void DetailReqMessage_ImpDetail::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 DetailReqMessage_ImpDetail::height() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.ImpDetail.height)
  return height_;
}
inline void DetailReqMessage_ImpDetail::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.ImpDetail.height)
}

// -------------------------------------------------------------------

// DetailReqMessage_Policy

// required int32 id = 1;
inline bool DetailReqMessage_Policy::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetailReqMessage_Policy::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DetailReqMessage_Policy::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DetailReqMessage_Policy::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DetailReqMessage_Policy::id() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.Policy.id)
  return id_;
}
inline void DetailReqMessage_Policy::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.Policy.id)
}

// optional int32 nbr = 2;
inline bool DetailReqMessage_Policy::has_nbr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetailReqMessage_Policy::set_has_nbr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DetailReqMessage_Policy::clear_has_nbr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DetailReqMessage_Policy::clear_nbr() {
  nbr_ = 0;
  clear_has_nbr();
}
inline ::google::protobuf::int32 DetailReqMessage_Policy::nbr() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.Policy.nbr)
  return nbr_;
}
inline void DetailReqMessage_Policy::set_nbr(::google::protobuf::int32 value) {
  set_has_nbr();
  nbr_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.Policy.nbr)
}

// -------------------------------------------------------------------

// DetailReqMessage

// optional string version = 1 [default = "1.0.6"];
inline bool DetailReqMessage::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetailReqMessage::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DetailReqMessage::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DetailReqMessage::clear_version() {
  if (version_ != _default_version_) {
    version_->assign(*_default_version_);
  }
  clear_has_version();
}
inline const ::std::string& DetailReqMessage::version() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.version)
  return *version_;
}
inline void DetailReqMessage::set_version(const ::std::string& value) {
  set_has_version();
  if (version_ == _default_version_) {
    version_ = new ::std::string;
  }
  version_->assign(value);
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.version)
}
inline void DetailReqMessage::set_version(const char* value) {
  set_has_version();
  if (version_ == _default_version_) {
    version_ = new ::std::string;
  }
  version_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.pxene.proto.DetailReqMessage.version)
}
inline void DetailReqMessage::set_version(const char* value, size_t size) {
  set_has_version();
  if (version_ == _default_version_) {
    version_ = new ::std::string;
  }
  version_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.pxene.proto.DetailReqMessage.version)
}
inline ::std::string* DetailReqMessage::mutable_version() {
  set_has_version();
  if (version_ == _default_version_) {
    version_ = new ::std::string(*_default_version_);
  }
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.version)
  return version_;
}
inline ::std::string* DetailReqMessage::release_version() {
  clear_has_version();
  if (version_ == _default_version_) {
    return NULL;
  } else {
    ::std::string* temp = version_;
    version_ = const_cast< ::std::string*>(_default_version_);
    return temp;
  }
}
inline void DetailReqMessage::set_allocated_version(::std::string* version) {
  if (version_ != _default_version_) {
    delete version_;
  }
  if (version) {
    set_has_version();
    version_ = version;
  } else {
    clear_has_version();
    version_ = const_cast< ::std::string*>(_default_version_);
  }
  // @@protoc_insertion_point(field_set_allocated:com.pxene.proto.DetailReqMessage.version)
}

// optional string bid_server_flag = 2;
inline bool DetailReqMessage::has_bid_server_flag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetailReqMessage::set_has_bid_server_flag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DetailReqMessage::clear_has_bid_server_flag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DetailReqMessage::clear_bid_server_flag() {
  if (bid_server_flag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    bid_server_flag_->clear();
  }
  clear_has_bid_server_flag();
}
inline const ::std::string& DetailReqMessage::bid_server_flag() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.bid_server_flag)
  return *bid_server_flag_;
}
inline void DetailReqMessage::set_bid_server_flag(const ::std::string& value) {
  set_has_bid_server_flag();
  if (bid_server_flag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    bid_server_flag_ = new ::std::string;
  }
  bid_server_flag_->assign(value);
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.bid_server_flag)
}
inline void DetailReqMessage::set_bid_server_flag(const char* value) {
  set_has_bid_server_flag();
  if (bid_server_flag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    bid_server_flag_ = new ::std::string;
  }
  bid_server_flag_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.pxene.proto.DetailReqMessage.bid_server_flag)
}
inline void DetailReqMessage::set_bid_server_flag(const char* value, size_t size) {
  set_has_bid_server_flag();
  if (bid_server_flag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    bid_server_flag_ = new ::std::string;
  }
  bid_server_flag_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.pxene.proto.DetailReqMessage.bid_server_flag)
}
inline ::std::string* DetailReqMessage::mutable_bid_server_flag() {
  set_has_bid_server_flag();
  if (bid_server_flag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    bid_server_flag_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.bid_server_flag)
  return bid_server_flag_;
}
inline ::std::string* DetailReqMessage::release_bid_server_flag() {
  clear_has_bid_server_flag();
  if (bid_server_flag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = bid_server_flag_;
    bid_server_flag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DetailReqMessage::set_allocated_bid_server_flag(::std::string* bid_server_flag) {
  if (bid_server_flag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete bid_server_flag_;
  }
  if (bid_server_flag) {
    set_has_bid_server_flag();
    bid_server_flag_ = bid_server_flag;
  } else {
    clear_has_bid_server_flag();
    bid_server_flag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.pxene.proto.DetailReqMessage.bid_server_flag)
}

// optional string requestId = 3;
inline bool DetailReqMessage::has_requestid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DetailReqMessage::set_has_requestid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DetailReqMessage::clear_has_requestid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DetailReqMessage::clear_requestid() {
  if (requestid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    requestid_->clear();
  }
  clear_has_requestid();
}
inline const ::std::string& DetailReqMessage::requestid() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.requestId)
  return *requestid_;
}
inline void DetailReqMessage::set_requestid(const ::std::string& value) {
  set_has_requestid();
  if (requestid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    requestid_ = new ::std::string;
  }
  requestid_->assign(value);
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.requestId)
}
inline void DetailReqMessage::set_requestid(const char* value) {
  set_has_requestid();
  if (requestid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    requestid_ = new ::std::string;
  }
  requestid_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.pxene.proto.DetailReqMessage.requestId)
}
inline void DetailReqMessage::set_requestid(const char* value, size_t size) {
  set_has_requestid();
  if (requestid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    requestid_ = new ::std::string;
  }
  requestid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.pxene.proto.DetailReqMessage.requestId)
}
inline ::std::string* DetailReqMessage::mutable_requestid() {
  set_has_requestid();
  if (requestid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    requestid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.requestId)
  return requestid_;
}
inline ::std::string* DetailReqMessage::release_requestid() {
  clear_has_requestid();
  if (requestid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = requestid_;
    requestid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DetailReqMessage::set_allocated_requestid(::std::string* requestid) {
  if (requestid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete requestid_;
  }
  if (requestid) {
    set_has_requestid();
    requestid_ = requestid;
  } else {
    clear_has_requestid();
    requestid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.pxene.proto.DetailReqMessage.requestId)
}

// optional int64 time = 4;
inline bool DetailReqMessage::has_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DetailReqMessage::set_has_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DetailReqMessage::clear_has_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DetailReqMessage::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::int64 DetailReqMessage::time() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.time)
  return time_;
}
inline void DetailReqMessage::set_time(::google::protobuf::int64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.time)
}

// optional int32 adxid = 5;
inline bool DetailReqMessage::has_adxid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DetailReqMessage::set_has_adxid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DetailReqMessage::clear_has_adxid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DetailReqMessage::clear_adxid() {
  adxid_ = 0;
  clear_has_adxid();
}
inline ::google::protobuf::int32 DetailReqMessage::adxid() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.adxid)
  return adxid_;
}
inline void DetailReqMessage::set_adxid(::google::protobuf::int32 value) {
  set_has_adxid();
  adxid_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.adxid)
}

// optional string appid = 6;
inline bool DetailReqMessage::has_appid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DetailReqMessage::set_has_appid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DetailReqMessage::clear_has_appid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DetailReqMessage::clear_appid() {
  if (appid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appid_->clear();
  }
  clear_has_appid();
}
inline const ::std::string& DetailReqMessage::appid() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.appid)
  return *appid_;
}
inline void DetailReqMessage::set_appid(const ::std::string& value) {
  set_has_appid();
  if (appid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appid_ = new ::std::string;
  }
  appid_->assign(value);
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.appid)
}
inline void DetailReqMessage::set_appid(const char* value) {
  set_has_appid();
  if (appid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appid_ = new ::std::string;
  }
  appid_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.pxene.proto.DetailReqMessage.appid)
}
inline void DetailReqMessage::set_appid(const char* value, size_t size) {
  set_has_appid();
  if (appid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appid_ = new ::std::string;
  }
  appid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.pxene.proto.DetailReqMessage.appid)
}
inline ::std::string* DetailReqMessage::mutable_appid() {
  set_has_appid();
  if (appid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.appid)
  return appid_;
}
inline ::std::string* DetailReqMessage::release_appid() {
  clear_has_appid();
  if (appid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = appid_;
    appid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DetailReqMessage::set_allocated_appid(::std::string* appid) {
  if (appid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete appid_;
  }
  if (appid) {
    set_has_appid();
    appid_ = appid;
  } else {
    clear_has_appid();
    appid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.pxene.proto.DetailReqMessage.appid)
}

// optional int32 devicetype = 9;
inline bool DetailReqMessage::has_devicetype() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void DetailReqMessage::set_has_devicetype() {
  _has_bits_[0] |= 0x00000040u;
}
inline void DetailReqMessage::clear_has_devicetype() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void DetailReqMessage::clear_devicetype() {
  devicetype_ = 0;
  clear_has_devicetype();
}
inline ::google::protobuf::int32 DetailReqMessage::devicetype() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.devicetype)
  return devicetype_;
}
inline void DetailReqMessage::set_devicetype(::google::protobuf::int32 value) {
  set_has_devicetype();
  devicetype_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.devicetype)
}

// optional int32 os = 10;
inline bool DetailReqMessage::has_os() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void DetailReqMessage::set_has_os() {
  _has_bits_[0] |= 0x00000080u;
}
inline void DetailReqMessage::clear_has_os() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void DetailReqMessage::clear_os() {
  os_ = 0;
  clear_has_os();
}
inline ::google::protobuf::int32 DetailReqMessage::os() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.os)
  return os_;
}
inline void DetailReqMessage::set_os(::google::protobuf::int32 value) {
  set_has_os();
  os_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.os)
}

// optional int64 city = 11;
inline bool DetailReqMessage::has_city() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void DetailReqMessage::set_has_city() {
  _has_bits_[0] |= 0x00000100u;
}
inline void DetailReqMessage::clear_has_city() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void DetailReqMessage::clear_city() {
  city_ = GOOGLE_LONGLONG(0);
  clear_has_city();
}
inline ::google::protobuf::int64 DetailReqMessage::city() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.city)
  return city_;
}
inline void DetailReqMessage::set_city(::google::protobuf::int64 value) {
  set_has_city();
  city_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.city)
}

// optional int32 connectiontype = 12;
inline bool DetailReqMessage::has_connectiontype() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void DetailReqMessage::set_has_connectiontype() {
  _has_bits_[0] |= 0x00000200u;
}
inline void DetailReqMessage::clear_has_connectiontype() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void DetailReqMessage::clear_connectiontype() {
  connectiontype_ = 0;
  clear_has_connectiontype();
}
inline ::google::protobuf::int32 DetailReqMessage::connectiontype() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.connectiontype)
  return connectiontype_;
}
inline void DetailReqMessage::set_connectiontype(::google::protobuf::int32 value) {
  set_has_connectiontype();
  connectiontype_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.connectiontype)
}

// optional int32 carrier = 13;
inline bool DetailReqMessage::has_carrier() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void DetailReqMessage::set_has_carrier() {
  _has_bits_[0] |= 0x00000400u;
}
inline void DetailReqMessage::clear_has_carrier() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void DetailReqMessage::clear_carrier() {
  carrier_ = 0;
  clear_has_carrier();
}
inline ::google::protobuf::int32 DetailReqMessage::carrier() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.carrier)
  return carrier_;
}
inline void DetailReqMessage::set_carrier(::google::protobuf::int32 value) {
  set_has_carrier();
  carrier_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.carrier)
}

// optional int32 nbr = 14;
inline bool DetailReqMessage::has_nbr() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void DetailReqMessage::set_has_nbr() {
  _has_bits_[0] |= 0x00000800u;
}
inline void DetailReqMessage::clear_has_nbr() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void DetailReqMessage::clear_nbr() {
  nbr_ = 0;
  clear_has_nbr();
}
inline ::google::protobuf::int32 DetailReqMessage::nbr() const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.nbr)
  return nbr_;
}
inline void DetailReqMessage::set_nbr(::google::protobuf::int32 value) {
  set_has_nbr();
  nbr_ = value;
  // @@protoc_insertion_point(field_set:com.pxene.proto.DetailReqMessage.nbr)
}

// repeated .com.pxene.proto.DetailReqMessage.ImpDetail impBidDetail = 15;
inline int DetailReqMessage::impbiddetail_size() const {
  return impbiddetail_.size();
}
inline void DetailReqMessage::clear_impbiddetail() {
  impbiddetail_.Clear();
}
inline const ::com::pxene::proto::DetailReqMessage_ImpDetail& DetailReqMessage::impbiddetail(int index) const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.impBidDetail)
  return impbiddetail_.Get(index);
}
inline ::com::pxene::proto::DetailReqMessage_ImpDetail* DetailReqMessage::mutable_impbiddetail(int index) {
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.impBidDetail)
  return impbiddetail_.Mutable(index);
}
inline ::com::pxene::proto::DetailReqMessage_ImpDetail* DetailReqMessage::add_impbiddetail() {
  // @@protoc_insertion_point(field_add:com.pxene.proto.DetailReqMessage.impBidDetail)
  return impbiddetail_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail >&
DetailReqMessage::impbiddetail() const {
  // @@protoc_insertion_point(field_list:com.pxene.proto.DetailReqMessage.impBidDetail)
  return impbiddetail_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_ImpDetail >*
DetailReqMessage::mutable_impbiddetail() {
  // @@protoc_insertion_point(field_mutable_list:com.pxene.proto.DetailReqMessage.impBidDetail)
  return &impbiddetail_;
}

// repeated .com.pxene.proto.DetailReqMessage.Policy policies = 16;
inline int DetailReqMessage::policies_size() const {
  return policies_.size();
}
inline void DetailReqMessage::clear_policies() {
  policies_.Clear();
}
inline const ::com::pxene::proto::DetailReqMessage_Policy& DetailReqMessage::policies(int index) const {
  // @@protoc_insertion_point(field_get:com.pxene.proto.DetailReqMessage.policies)
  return policies_.Get(index);
}
inline ::com::pxene::proto::DetailReqMessage_Policy* DetailReqMessage::mutable_policies(int index) {
  // @@protoc_insertion_point(field_mutable:com.pxene.proto.DetailReqMessage.policies)
  return policies_.Mutable(index);
}
inline ::com::pxene::proto::DetailReqMessage_Policy* DetailReqMessage::add_policies() {
  // @@protoc_insertion_point(field_add:com.pxene.proto.DetailReqMessage.policies)
  return policies_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_Policy >&
DetailReqMessage::policies() const {
  // @@protoc_insertion_point(field_list:com.pxene.proto.DetailReqMessage.policies)
  return policies_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::pxene::proto::DetailReqMessage_Policy >*
DetailReqMessage::mutable_policies() {
  // @@protoc_insertion_point(field_mutable_list:com.pxene.proto.DetailReqMessage.policies)
  return &policies_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace pxene
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_detail_5finfo_2eproto__INCLUDED
