// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zplay_adx_rtb.proto

#ifndef PROTOBUF_zplay_5fadx_5frtb_2eproto__INCLUDED
#define PROTOBUF_zplay_5fadx_5frtb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "openrtb.pb.h"
// @@protoc_insertion_point(includes)

namespace zadx {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_zplay_5fadx_5frtb_2eproto();
void protobuf_AssignDesc_zplay_5fadx_5frtb_2eproto();
void protobuf_ShutdownFile_zplay_5fadx_5frtb_2eproto();


// ===================================================================


// ===================================================================

static const int kVersionFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  version;
static const int kIsPingFieldNumber = 202;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  is_ping;
static const int kNeedHttpsFieldNumber = 203;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  need_https;
static const int kAccuFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Geo,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  accu;
static const int kStreetFieldNumber = 201;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Geo,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  street;
static const int kIsSplashScreenFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Imp,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  is_splash_screen;
static const int kInventoryTypesFieldNumber = 201;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Imp,
    ::google::protobuf::internal::RepeatedPrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  inventory_types;
static const int kPlmnFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Device,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  plmn;
static const int kImeiFieldNumber = 201;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Device,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  imei;
static const int kMacFieldNumber = 202;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Device,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  mac;
static const int kAndroidIdFieldNumber = 203;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Device,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  android_id;
static const int kAdidFieldNumber = 204;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Device,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  adid;
static const int kOrientationFieldNumber = 205;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Device,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  orientation;
static const int kImsiFieldNumber = 206;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidRequest_Device,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  imsi;
static const int kImptrackersFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  imptrackers;
static const int kClktrackersFieldNumber = 201;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::RepeatedStringTypeTraits, 9, false >
  clktrackers;
static const int kClkurlFieldNumber = 202;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  clkurl;
static const int kHtmlSnippetFieldNumber = 203;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  html_snippet;
static const int kAppVerFieldNumber = 204;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  app_ver;
static const int kInventoryTypeFieldNumber = 205;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  inventory_type;
static const int kTitleFieldNumber = 206;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  title;
static const int kDescFieldNumber = 207;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  desc;
static const int kActionFieldNumber = 208;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  action;
static const int kDownloadFileNameFieldNumber = 209;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::BidResponse_SeatBid_Bid,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  download_file_name;
static const int kLinkTypeFieldNumber = 200;
extern ::google::protobuf::internal::ExtensionIdentifier< ::com::google::openrtb::NativeResponse_Link,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  link_type;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace zadx

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_zplay_5fadx_5frtb_2eproto__INCLUDED
